backend:
  - 'packages/**/package.json'
  - 'packages/**/server/**/*.(js|ts)'
  - 'packages/**/strapi-server.js'
  - 'packages/{utils,generators,cli,providers}/**'
  - 'packages/core/*/{lib,bin,ee}/**'
  - 'api-tests/**'
frontend:
  - 'packages/**/package.json'
  - 'packages/**/admin/src/**'
  - 'packages/**/strapi-admin.js'
  - 'pacakges/core/helper-plugin/**'
  - 'pacakges/admin-test-utils/**'
