backend:
  - 'packages/**/package.json'
  - 'packages/**/server/**'
  - 'packages/**/strapi-server.js'
  - 'packages/providers/**'
  - 'packages/utils/**'
  - 'packages/generators/**'
  - 'packages/cli/**'
  - 'api-tests/**'
  - 'packages/core/*/lib/**'
  - 'packages/core/*/bin/**'
  - 'packages/core/*/ee/**'
frontend:
  - 'packages/**/package.json'
  - 'packages/**/admin/src/**'
  - 'packages/**/strapi-admin.js'
  - 'pacakges/core/helper-plugin/**'
  - 'pacakges/admin-test-utils/**'
