nodeLinker: node-modules

enableGlobalCache: false

nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

defaultSemverRangePrefix: ''

compressionLevel: 0

preferInteractive: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs
