version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '5432:5432'

  mysql:
    image: mysql:5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'

  app:
    container_name: strapi-app
    image: node:18
    volumes:
      - /Users/nathanpichon/WebstormProjects/strapi/examples/getstarted:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '2000:1337'
    command: >
      sh -c "npm install && npm run build && npm run develop"

volumes:
  pgdata:
  mysqldata:
