name: 'Checks'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    branches:
      - main
      - develop

jobs:
  check-pr-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-pr-status

  # pnpm is not subject to the same issue as yarn https://github.com/pnpm/pnpm/issues/4361
  # security-lockfile-analysis:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #     - uses: ./.github/actions/security/lockfile
  #       with:
  #         allowedHosts: 'yarn'
