# name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ec2-user

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: yarn install

    - name: Build Strapi
      run: yarn build

    - name: Deploy to EC2
      env:
        EC2_PUBLIC_DNS: ${{ secrets.EC2_PUBLIC_DNS }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem
        scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./* ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_DNS }}:/home/ubuntu/strapi/
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_DNS }} 'cd /home/ubuntu/strapi && yarn install && yarn build && pm2 restart strapi'
