name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Publish
        run: ./node_modules/.bin/lerna publish --force-publish --dist-tag latest --exact "$version" --yes
        env:
          VERSION: '${{ inputs.version }}'
      - name: Changelog
        run: npx @sclt/program-changelog --owner strapi --repo strapi --version ${{ inputs.version }}
